site_name: Pi-Server-VM Documentation
theme:
  name: material
  # --- START OF NEW SECTION ---
  # This section enables extra features of the Material theme.
  # We are telling it to load the necessary JavaScript for Mermaid.
  features:
    - navigation.tabs
    - content.code.annotate
    - mermaid
  # --- END OF NEW SECTION ---

nav:
  - 'Home': 'index.md'
  - 'Installation':
      - 'Windows': 'install/INSTALL_WINDOWS.md'
      - 'macOS': 'install/INSTALL_MACOS.md'
      - 'Linux': 'install/INSTALL_LINUX.md'
  - 'Contributing': 'CONTRIBUTING.md'

# This section is correct and remains the same.
markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
