# .github/workflows/build_release.yml

name: Create GitHub Release with Cross-Platform Executables

on:
    push:
        tags:
            - "v*.*.*" # Runs on version tags like v1.3.1, v1.4.0, etc.

permissions:
    contents: write

jobs:
    build:
        name: Build on ${{ matrix.os }}
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-latest, macos-latest, windows-latest]

        steps:
            - name: Check out the repository code
              uses: actions/checkout@v4

            - name: Set up Python 3.11
              uses: actions/setup-python@v5
              with:
                  python-version: "3.11"

            - name: Install dependencies
              run: pip install -e .[dev]

            - name: Build executables with PyInstaller
              run: python build.py

            # --- CORRECTED ARTIFACT PREPARATION ---
            - name: Package executables for release
              run: |
                  if [ "$RUNNER_OS" == "Windows" ]; then
                    # For Windows, create a .zip archive
                    7z a executables-Windows.zip ./dist/*
                  else
                    # For Linux and macOS, create a .tar.gz archive
                    # This preserves executable permissions.
                    tar -czvf executables-${{ runner.os }}.tar.gz -C dist .
                  fi
              shell: bash

            # --- CORRECTED ARTIFACT UPLOAD ---
            - name: Upload build artifact
              uses: actions/upload-artifact@v4
              with:
                  # The name is now generic, the path will be specific
                  name: executables-${{ runner.os }}
                  # Use a wildcard to find the correct archive type
                  path: executables-${{ runner.os }}.*

    release:
        name: Create GitHub Release
        runs-on: ubuntu-latest
        needs: build

        steps:
            - name: Download all build artifacts
              uses: actions/download-artifact@v4
              with:
                  path: artifacts

            # --- CORRECTED FILE UPLOAD ---
            - name: Create Release and Upload Assets
              uses: softprops/action-gh-release@v2
              with:
                  generate_release_notes: true
                  # Use a glob pattern to find all archive types (.zip and .tar.gz)
                  files: artifacts/**/*.*
