# .github/workflows/build_release.yml (Final, Definitive Version)

name: Create GitHub Release with Cross-Platform Executables

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  build:
    name: Build on ${{ matrix.os-name }}
    runs-on: ${{ matrix.os-vtu }}
    strategy:
      matrix:
        include:
          - os-name: Linux
            os-vtu: ubuntu-latest
            asset-ext: tar.gz
          - os-name: macOS
            os-vtu: macos-latest
            asset-ext: tar.gz
          - os-name: Windows
            os-vtu: windows-latest
            asset-ext: zip

    steps:
      - name: Check out the repository code
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install uv
        run: pipx install uv

      - name: Install dependencies with uv
        run: uv pip install --system -e .[dev]

      # --- FORENSIC STEP: Find the true location of python311.dll on Windows ---
      # This step runs ONLY on the Windows builder. It finds the exact path to the
      # DLL and saves it as an output variable for the build step.
      - name: Find the location of python311.dll on Windows
        if: runner.os == 'Windows'
        id: find_dll
        run: |
          echo "Searching for python311.dll in ${{ env.pythonLocation }}..."
          $dll_path = (Get-ChildItem -Path ${{ env.pythonLocation }} -Recurse -Filter python311.dll).FullName
          if ($dll_path) {
            echo "Found DLL at: $dll_path"
            echo "dll_path=$dll_path" >> $env:GITHUB_OUTPUT
          } else {
            echo "FATAL: python311.dll not found!"
            exit 1
          }
        shell: pwsh

      # --- Build Step with Environment Variable ---
      - name: Build executables with PyInstaller
        # The 'env' block makes the DLL path from the previous step available
        # as an environment variable that our intelligent .spec file can read.
        env:
          WIN_PYTHON_DLL_PATH: ${{ steps.find_dll.outputs.dll_path }}
        run: python build.py

      - name: Create package directory
        run: mkdir package

      - name: Create Archive
        uses: thedoctor0/zip-release@master
        with:
          type: '${{ matrix.asset-ext }}'
          directory: 'dist'
          filename: '../package/executables-${{ matrix.os-name }}.${{ matrix.asset-ext }}'

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: executables-${{ matrix.os-name }}
          path: ./package/*

  release:
    name: Create GitHub Release
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download all build artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Create Release and Upload Assets
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          files: artifacts/**/*
